# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vis_pb2 as vis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisualizerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.clientTextQuery = channel.stream_unary(
                '/xrVis.VisualizerServer/clientTextQuery',
                request_serializer=vis__pb2.AudioFile.SerializeToString,
                response_deserializer=vis__pb2.allPointClouds.FromString,
                _registered_method=True)
        self.updateMap = channel.unary_unary(
                '/xrVis.VisualizerServer/updateMap',
                request_serializer=vis__pb2.Status.SerializeToString,
                response_deserializer=vis__pb2.Status.FromString,
                _registered_method=True)
        self.updateDeviceMap = channel.stream_unary(
                '/xrVis.VisualizerServer/updateDeviceMap',
                request_serializer=vis__pb2.objectUpdate.SerializeToString,
                response_deserializer=vis__pb2.Status.FromString,
                _registered_method=True)


class VisualizerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def clientTextQuery(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateDeviceMap(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisualizerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'clientTextQuery': grpc.stream_unary_rpc_method_handler(
                    servicer.clientTextQuery,
                    request_deserializer=vis__pb2.AudioFile.FromString,
                    response_serializer=vis__pb2.allPointClouds.SerializeToString,
            ),
            'updateMap': grpc.unary_unary_rpc_method_handler(
                    servicer.updateMap,
                    request_deserializer=vis__pb2.Status.FromString,
                    response_serializer=vis__pb2.Status.SerializeToString,
            ),
            'updateDeviceMap': grpc.stream_unary_rpc_method_handler(
                    servicer.updateDeviceMap,
                    request_deserializer=vis__pb2.objectUpdate.FromString,
                    response_serializer=vis__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xrVis.VisualizerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xrVis.VisualizerServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisualizerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def clientTextQuery(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xrVis.VisualizerServer/clientTextQuery',
            vis__pb2.AudioFile.SerializeToString,
            vis__pb2.allPointClouds.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xrVis.VisualizerServer/updateMap',
            vis__pb2.Status.SerializeToString,
            vis__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateDeviceMap(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xrVis.VisualizerServer/updateDeviceMap',
            vis__pb2.objectUpdate.SerializeToString,
            vis__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
