name: semanticxr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - plotly
  - pillow
  - pip
  - pip:
      - av
      - grpcio
      - open3d
      - protobuf
