# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import xr_service_pb2 as xr__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xr_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class XrServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadSyncMessage_dataset = channel.stream_unary(
                '/xr.XrService/UploadSyncMessage_dataset',
                request_serializer=xr__service__pb2.UpstreamSyncMessage_dataset.SerializeToString,
                response_deserializer=xr__service__pb2.VideoStatus.FromString,
                _registered_method=True)
        self.UploadSyncMessage = channel.stream_unary(
                '/xr.XrService/UploadSyncMessage',
                request_serializer=xr__service__pb2.UpstreamSyncMessage.SerializeToString,
                response_deserializer=xr__service__pb2.VideoStatus.FromString,
                _registered_method=True)
        self.UploadSyncMessage_quest = channel.stream_unary(
                '/xr.XrService/UploadSyncMessage_quest',
                request_serializer=xr__service__pb2.UpstreamSyncMessage_quest.SerializeToString,
                response_deserializer=xr__service__pb2.VideoStatus.FromString,
                _registered_method=True)


class XrServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadSyncMessage_dataset(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSyncMessage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSyncMessage_quest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadSyncMessage_dataset': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadSyncMessage_dataset,
                    request_deserializer=xr__service__pb2.UpstreamSyncMessage_dataset.FromString,
                    response_serializer=xr__service__pb2.VideoStatus.SerializeToString,
            ),
            'UploadSyncMessage': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadSyncMessage,
                    request_deserializer=xr__service__pb2.UpstreamSyncMessage.FromString,
                    response_serializer=xr__service__pb2.VideoStatus.SerializeToString,
            ),
            'UploadSyncMessage_quest': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadSyncMessage_quest,
                    request_deserializer=xr__service__pb2.UpstreamSyncMessage_quest.FromString,
                    response_serializer=xr__service__pb2.VideoStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xr.XrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xr.XrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class XrService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadSyncMessage_dataset(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xr.XrService/UploadSyncMessage_dataset',
            xr__service__pb2.UpstreamSyncMessage_dataset.SerializeToString,
            xr__service__pb2.VideoStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadSyncMessage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xr.XrService/UploadSyncMessage',
            xr__service__pb2.UpstreamSyncMessage.SerializeToString,
            xr__service__pb2.VideoStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadSyncMessage_quest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xr.XrService/UploadSyncMessage_quest',
            xr__service__pb2.UpstreamSyncMessage_quest.SerializeToString,
            xr__service__pb2.VideoStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
