// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vis.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace XrVis {

  /// <summary>Holder for reflection information generated from vis.proto</summary>
  public static partial class VisReflection {

    #region Descriptor
    /// <summary>File descriptor for vis.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VisReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgl2aXMucHJvdG8SBXhyVmlzIkIKClBvaW50Q2xvdWQSDgoGcG9pbnRzGAEg",
            "AygCEhIKCm51bV9wb2ludHMYAyABKAUSEAoIY2VudHJvaWQYBCADKAIikgEK",
            "DmFsbFBvaW50Q2xvdWRzEiYKC3BvaW50Q2xvdWRzGAEgAygLMhEueHJWaXMu",
            "UG9pbnRDbG91ZBIOCgZjb2xvcnMYAiADKAISFgoObnVtUG9pbnRDbG91ZHMY",
            "AyABKAUSHQoVc2VydmVyUXVlcnlQcm9jZXNzaW5nGAQgASgCEhEKCXRleHRR",
            "dWVyeRgFIAEoCSJ5CgdPYmplY3RzEhIKCnBvaW50Q2xvdWQYASADKAISDAoE",
            "QkJveBgCIAMoAhIXCg9jbGlwX2VtYmVkZGluZ3MYAyADKAISEgoKbnVtX3Bv",
            "aW50cxgEIAEoBRIQCghjZW50cm9pZBgFIAMoAhINCgVpbmRleBgGIAEoBSKo",
            "AQoMb2JqZWN0VXBkYXRlEh8KB29iamVjdHMYASADKAsyDi54clZpcy5PYmpl",
            "Y3RzEhMKC251bV9vYmplY3RzGAIgASgFEhYKDnJlbW92ZV9pbmRpY2VzGAMg",
            "AygFEhwKFHNlcnZlclByb2Nlc3NMYXRlbmN5GAQgASgCEhMKC2ZyYW1lTnVt",
            "YmVyGAUgAygFEhcKD2NsaWVudFRpbWVTdGFtcBgGIAEoAyIZCgZTdGF0dXMS",
            "DwoHbWVzc2FnZRgBIAEoCCIyCglBdWRpb0ZpbGUSEgoKY2h1bmtfZGF0YRgB",
            "IAEoDBIRCgl0ZXh0UXVlcnkYAiABKAkytAEKEFZpc3VhbGl6ZXJTZXJ2ZXIS",
            "PAoPY2xpZW50VGV4dFF1ZXJ5EhAueHJWaXMuQXVkaW9GaWxlGhUueHJWaXMu",
            "YWxsUG9pbnRDbG91ZHMoARIpCgl1cGRhdGVNYXASDS54clZpcy5TdGF0dXMa",
            "DS54clZpcy5TdGF0dXMSNwoPdXBkYXRlRGV2aWNlTWFwEhMueHJWaXMub2Jq",
            "ZWN0VXBkYXRlGg0ueHJWaXMuU3RhdHVzKAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.PointCloud), global::XrVis.PointCloud.Parser, new[]{ "Points", "NumPoints", "Centroid" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.allPointClouds), global::XrVis.allPointClouds.Parser, new[]{ "PointClouds", "Colors", "NumPointClouds", "ServerQueryProcessing", "TextQuery" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.Objects), global::XrVis.Objects.Parser, new[]{ "PointCloud", "BBox", "ClipEmbeddings", "NumPoints", "Centroid", "Index" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.objectUpdate), global::XrVis.objectUpdate.Parser, new[]{ "Objects", "NumObjects", "RemoveIndices", "ServerProcessLatency", "FrameNumber", "ClientTimeStamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.Status), global::XrVis.Status.Parser, new[]{ "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::XrVis.AudioFile), global::XrVis.AudioFile.Parser, new[]{ "ChunkData", "TextQuery" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PointCloud : pb::IMessage<PointCloud>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PointCloud> _parser = new pb::MessageParser<PointCloud>(() => new PointCloud());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PointCloud> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PointCloud() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PointCloud(PointCloud other) : this() {
      points_ = other.points_.Clone();
      numPoints_ = other.numPoints_;
      centroid_ = other.centroid_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PointCloud Clone() {
      return new PointCloud(this);
    }

    /// <summary>Field number for the "points" field.</summary>
    public const int PointsFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_points_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> points_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Points {
      get { return points_; }
    }

    /// <summary>Field number for the "num_points" field.</summary>
    public const int NumPointsFieldNumber = 3;
    private int numPoints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumPoints {
      get { return numPoints_; }
      set {
        numPoints_ = value;
      }
    }

    /// <summary>Field number for the "centroid" field.</summary>
    public const int CentroidFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_centroid_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> centroid_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Centroid {
      get { return centroid_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PointCloud);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PointCloud other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!points_.Equals(other.points_)) return false;
      if (NumPoints != other.NumPoints) return false;
      if(!centroid_.Equals(other.centroid_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= points_.GetHashCode();
      if (NumPoints != 0) hash ^= NumPoints.GetHashCode();
      hash ^= centroid_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      points_.WriteTo(output, _repeated_points_codec);
      if (NumPoints != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumPoints);
      }
      centroid_.WriteTo(output, _repeated_centroid_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      points_.WriteTo(ref output, _repeated_points_codec);
      if (NumPoints != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumPoints);
      }
      centroid_.WriteTo(ref output, _repeated_centroid_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += points_.CalculateSize(_repeated_points_codec);
      if (NumPoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumPoints);
      }
      size += centroid_.CalculateSize(_repeated_centroid_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PointCloud other) {
      if (other == null) {
        return;
      }
      points_.Add(other.points_);
      if (other.NumPoints != 0) {
        NumPoints = other.NumPoints;
      }
      centroid_.Add(other.centroid_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            points_.AddEntriesFrom(input, _repeated_points_codec);
            break;
          }
          case 24: {
            NumPoints = input.ReadInt32();
            break;
          }
          case 34:
          case 37: {
            centroid_.AddEntriesFrom(input, _repeated_centroid_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            points_.AddEntriesFrom(ref input, _repeated_points_codec);
            break;
          }
          case 24: {
            NumPoints = input.ReadInt32();
            break;
          }
          case 34:
          case 37: {
            centroid_.AddEntriesFrom(ref input, _repeated_centroid_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class allPointClouds : pb::IMessage<allPointClouds>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<allPointClouds> _parser = new pb::MessageParser<allPointClouds>(() => new allPointClouds());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<allPointClouds> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public allPointClouds() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public allPointClouds(allPointClouds other) : this() {
      pointClouds_ = other.pointClouds_.Clone();
      colors_ = other.colors_.Clone();
      numPointClouds_ = other.numPointClouds_;
      serverQueryProcessing_ = other.serverQueryProcessing_;
      textQuery_ = other.textQuery_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public allPointClouds Clone() {
      return new allPointClouds(this);
    }

    /// <summary>Field number for the "pointClouds" field.</summary>
    public const int PointCloudsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XrVis.PointCloud> _repeated_pointClouds_codec
        = pb::FieldCodec.ForMessage(10, global::XrVis.PointCloud.Parser);
    private readonly pbc::RepeatedField<global::XrVis.PointCloud> pointClouds_ = new pbc::RepeatedField<global::XrVis.PointCloud>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::XrVis.PointCloud> PointClouds {
      get { return pointClouds_; }
    }

    /// <summary>Field number for the "colors" field.</summary>
    public const int ColorsFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_colors_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> colors_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Colors {
      get { return colors_; }
    }

    /// <summary>Field number for the "numPointClouds" field.</summary>
    public const int NumPointCloudsFieldNumber = 3;
    private int numPointClouds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumPointClouds {
      get { return numPointClouds_; }
      set {
        numPointClouds_ = value;
      }
    }

    /// <summary>Field number for the "serverQueryProcessing" field.</summary>
    public const int ServerQueryProcessingFieldNumber = 4;
    private float serverQueryProcessing_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ServerQueryProcessing {
      get { return serverQueryProcessing_; }
      set {
        serverQueryProcessing_ = value;
      }
    }

    /// <summary>Field number for the "textQuery" field.</summary>
    public const int TextQueryFieldNumber = 5;
    private string textQuery_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TextQuery {
      get { return textQuery_; }
      set {
        textQuery_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as allPointClouds);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(allPointClouds other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pointClouds_.Equals(other.pointClouds_)) return false;
      if(!colors_.Equals(other.colors_)) return false;
      if (NumPointClouds != other.NumPointClouds) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ServerQueryProcessing, other.ServerQueryProcessing)) return false;
      if (TextQuery != other.TextQuery) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pointClouds_.GetHashCode();
      hash ^= colors_.GetHashCode();
      if (NumPointClouds != 0) hash ^= NumPointClouds.GetHashCode();
      if (ServerQueryProcessing != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ServerQueryProcessing);
      if (TextQuery.Length != 0) hash ^= TextQuery.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pointClouds_.WriteTo(output, _repeated_pointClouds_codec);
      colors_.WriteTo(output, _repeated_colors_codec);
      if (NumPointClouds != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumPointClouds);
      }
      if (ServerQueryProcessing != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(ServerQueryProcessing);
      }
      if (TextQuery.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TextQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pointClouds_.WriteTo(ref output, _repeated_pointClouds_codec);
      colors_.WriteTo(ref output, _repeated_colors_codec);
      if (NumPointClouds != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumPointClouds);
      }
      if (ServerQueryProcessing != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(ServerQueryProcessing);
      }
      if (TextQuery.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TextQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pointClouds_.CalculateSize(_repeated_pointClouds_codec);
      size += colors_.CalculateSize(_repeated_colors_codec);
      if (NumPointClouds != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumPointClouds);
      }
      if (ServerQueryProcessing != 0F) {
        size += 1 + 4;
      }
      if (TextQuery.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextQuery);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(allPointClouds other) {
      if (other == null) {
        return;
      }
      pointClouds_.Add(other.pointClouds_);
      colors_.Add(other.colors_);
      if (other.NumPointClouds != 0) {
        NumPointClouds = other.NumPointClouds;
      }
      if (other.ServerQueryProcessing != 0F) {
        ServerQueryProcessing = other.ServerQueryProcessing;
      }
      if (other.TextQuery.Length != 0) {
        TextQuery = other.TextQuery;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pointClouds_.AddEntriesFrom(input, _repeated_pointClouds_codec);
            break;
          }
          case 18:
          case 21: {
            colors_.AddEntriesFrom(input, _repeated_colors_codec);
            break;
          }
          case 24: {
            NumPointClouds = input.ReadInt32();
            break;
          }
          case 37: {
            ServerQueryProcessing = input.ReadFloat();
            break;
          }
          case 42: {
            TextQuery = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            pointClouds_.AddEntriesFrom(ref input, _repeated_pointClouds_codec);
            break;
          }
          case 18:
          case 21: {
            colors_.AddEntriesFrom(ref input, _repeated_colors_codec);
            break;
          }
          case 24: {
            NumPointClouds = input.ReadInt32();
            break;
          }
          case 37: {
            ServerQueryProcessing = input.ReadFloat();
            break;
          }
          case 42: {
            TextQuery = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Objects : pb::IMessage<Objects>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Objects> _parser = new pb::MessageParser<Objects>(() => new Objects());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Objects> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Objects() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Objects(Objects other) : this() {
      pointCloud_ = other.pointCloud_.Clone();
      bBox_ = other.bBox_.Clone();
      clipEmbeddings_ = other.clipEmbeddings_.Clone();
      numPoints_ = other.numPoints_;
      centroid_ = other.centroid_.Clone();
      index_ = other.index_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Objects Clone() {
      return new Objects(this);
    }

    /// <summary>Field number for the "pointCloud" field.</summary>
    public const int PointCloudFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_pointCloud_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> pointCloud_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Array of floats. 3 floats per point
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> PointCloud {
      get { return pointCloud_; }
    }

    /// <summary>Field number for the "BBox" field.</summary>
    public const int BBoxFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_bBox_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> bBox_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// must be another array of Points. 8 points, or 2 or 3 points? Each point is 3 floats
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> BBox {
      get { return bBox_; }
    }

    /// <summary>Field number for the "clip_embeddings" field.</summary>
    public const int ClipEmbeddingsFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_clipEmbeddings_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> clipEmbeddings_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// 1024 floats
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> ClipEmbeddings {
      get { return clipEmbeddings_; }
    }

    /// <summary>Field number for the "num_points" field.</summary>
    public const int NumPointsFieldNumber = 4;
    private int numPoints_;
    /// <summary>
    /// number of points in the pointCloud. each point is 3 floats
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumPoints {
      get { return numPoints_; }
      set {
        numPoints_ = value;
      }
    }

    /// <summary>Field number for the "centroid" field.</summary>
    public const int CentroidFieldNumber = 5;
    private static readonly pb::FieldCodec<float> _repeated_centroid_codec
        = pb::FieldCodec.ForFloat(42);
    private readonly pbc::RepeatedField<float> centroid_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// 3 floats
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Centroid {
      get { return centroid_; }
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 6;
    private int index_;
    /// <summary>
    /// index of the object
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Objects);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Objects other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pointCloud_.Equals(other.pointCloud_)) return false;
      if(!bBox_.Equals(other.bBox_)) return false;
      if(!clipEmbeddings_.Equals(other.clipEmbeddings_)) return false;
      if (NumPoints != other.NumPoints) return false;
      if(!centroid_.Equals(other.centroid_)) return false;
      if (Index != other.Index) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pointCloud_.GetHashCode();
      hash ^= bBox_.GetHashCode();
      hash ^= clipEmbeddings_.GetHashCode();
      if (NumPoints != 0) hash ^= NumPoints.GetHashCode();
      hash ^= centroid_.GetHashCode();
      if (Index != 0) hash ^= Index.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pointCloud_.WriteTo(output, _repeated_pointCloud_codec);
      bBox_.WriteTo(output, _repeated_bBox_codec);
      clipEmbeddings_.WriteTo(output, _repeated_clipEmbeddings_codec);
      if (NumPoints != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumPoints);
      }
      centroid_.WriteTo(output, _repeated_centroid_codec);
      if (Index != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Index);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pointCloud_.WriteTo(ref output, _repeated_pointCloud_codec);
      bBox_.WriteTo(ref output, _repeated_bBox_codec);
      clipEmbeddings_.WriteTo(ref output, _repeated_clipEmbeddings_codec);
      if (NumPoints != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NumPoints);
      }
      centroid_.WriteTo(ref output, _repeated_centroid_codec);
      if (Index != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Index);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pointCloud_.CalculateSize(_repeated_pointCloud_codec);
      size += bBox_.CalculateSize(_repeated_bBox_codec);
      size += clipEmbeddings_.CalculateSize(_repeated_clipEmbeddings_codec);
      if (NumPoints != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumPoints);
      }
      size += centroid_.CalculateSize(_repeated_centroid_codec);
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Objects other) {
      if (other == null) {
        return;
      }
      pointCloud_.Add(other.pointCloud_);
      bBox_.Add(other.bBox_);
      clipEmbeddings_.Add(other.clipEmbeddings_);
      if (other.NumPoints != 0) {
        NumPoints = other.NumPoints;
      }
      centroid_.Add(other.centroid_);
      if (other.Index != 0) {
        Index = other.Index;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            pointCloud_.AddEntriesFrom(input, _repeated_pointCloud_codec);
            break;
          }
          case 18:
          case 21: {
            bBox_.AddEntriesFrom(input, _repeated_bBox_codec);
            break;
          }
          case 26:
          case 29: {
            clipEmbeddings_.AddEntriesFrom(input, _repeated_clipEmbeddings_codec);
            break;
          }
          case 32: {
            NumPoints = input.ReadInt32();
            break;
          }
          case 42:
          case 45: {
            centroid_.AddEntriesFrom(input, _repeated_centroid_codec);
            break;
          }
          case 48: {
            Index = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            pointCloud_.AddEntriesFrom(ref input, _repeated_pointCloud_codec);
            break;
          }
          case 18:
          case 21: {
            bBox_.AddEntriesFrom(ref input, _repeated_bBox_codec);
            break;
          }
          case 26:
          case 29: {
            clipEmbeddings_.AddEntriesFrom(ref input, _repeated_clipEmbeddings_codec);
            break;
          }
          case 32: {
            NumPoints = input.ReadInt32();
            break;
          }
          case 42:
          case 45: {
            centroid_.AddEntriesFrom(ref input, _repeated_centroid_codec);
            break;
          }
          case 48: {
            Index = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class objectUpdate : pb::IMessage<objectUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<objectUpdate> _parser = new pb::MessageParser<objectUpdate>(() => new objectUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<objectUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public objectUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public objectUpdate(objectUpdate other) : this() {
      objects_ = other.objects_.Clone();
      numObjects_ = other.numObjects_;
      removeIndices_ = other.removeIndices_.Clone();
      serverProcessLatency_ = other.serverProcessLatency_;
      frameNumber_ = other.frameNumber_.Clone();
      clientTimeStamp_ = other.clientTimeStamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public objectUpdate Clone() {
      return new objectUpdate(this);
    }

    /// <summary>Field number for the "objects" field.</summary>
    public const int ObjectsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::XrVis.Objects> _repeated_objects_codec
        = pb::FieldCodec.ForMessage(10, global::XrVis.Objects.Parser);
    private readonly pbc::RepeatedField<global::XrVis.Objects> objects_ = new pbc::RepeatedField<global::XrVis.Objects>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::XrVis.Objects> Objects {
      get { return objects_; }
    }

    /// <summary>Field number for the "num_objects" field.</summary>
    public const int NumObjectsFieldNumber = 2;
    private int numObjects_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumObjects {
      get { return numObjects_; }
      set {
        numObjects_ = value;
      }
    }

    /// <summary>Field number for the "remove_indices" field.</summary>
    public const int RemoveIndicesFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_removeIndices_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> removeIndices_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RemoveIndices {
      get { return removeIndices_; }
    }

    /// <summary>Field number for the "serverProcessLatency" field.</summary>
    public const int ServerProcessLatencyFieldNumber = 4;
    private float serverProcessLatency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float ServerProcessLatency {
      get { return serverProcessLatency_; }
      set {
        serverProcessLatency_ = value;
      }
    }

    /// <summary>Field number for the "frameNumber" field.</summary>
    public const int FrameNumberFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_frameNumber_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> frameNumber_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> FrameNumber {
      get { return frameNumber_; }
    }

    /// <summary>Field number for the "clientTimeStamp" field.</summary>
    public const int ClientTimeStampFieldNumber = 6;
    private long clientTimeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ClientTimeStamp {
      get { return clientTimeStamp_; }
      set {
        clientTimeStamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as objectUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(objectUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!objects_.Equals(other.objects_)) return false;
      if (NumObjects != other.NumObjects) return false;
      if(!removeIndices_.Equals(other.removeIndices_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ServerProcessLatency, other.ServerProcessLatency)) return false;
      if(!frameNumber_.Equals(other.frameNumber_)) return false;
      if (ClientTimeStamp != other.ClientTimeStamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= objects_.GetHashCode();
      if (NumObjects != 0) hash ^= NumObjects.GetHashCode();
      hash ^= removeIndices_.GetHashCode();
      if (ServerProcessLatency != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ServerProcessLatency);
      hash ^= frameNumber_.GetHashCode();
      if (ClientTimeStamp != 0L) hash ^= ClientTimeStamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      objects_.WriteTo(output, _repeated_objects_codec);
      if (NumObjects != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumObjects);
      }
      removeIndices_.WriteTo(output, _repeated_removeIndices_codec);
      if (ServerProcessLatency != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(ServerProcessLatency);
      }
      frameNumber_.WriteTo(output, _repeated_frameNumber_codec);
      if (ClientTimeStamp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ClientTimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      objects_.WriteTo(ref output, _repeated_objects_codec);
      if (NumObjects != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(NumObjects);
      }
      removeIndices_.WriteTo(ref output, _repeated_removeIndices_codec);
      if (ServerProcessLatency != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(ServerProcessLatency);
      }
      frameNumber_.WriteTo(ref output, _repeated_frameNumber_codec);
      if (ClientTimeStamp != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ClientTimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += objects_.CalculateSize(_repeated_objects_codec);
      if (NumObjects != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumObjects);
      }
      size += removeIndices_.CalculateSize(_repeated_removeIndices_codec);
      if (ServerProcessLatency != 0F) {
        size += 1 + 4;
      }
      size += frameNumber_.CalculateSize(_repeated_frameNumber_codec);
      if (ClientTimeStamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ClientTimeStamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(objectUpdate other) {
      if (other == null) {
        return;
      }
      objects_.Add(other.objects_);
      if (other.NumObjects != 0) {
        NumObjects = other.NumObjects;
      }
      removeIndices_.Add(other.removeIndices_);
      if (other.ServerProcessLatency != 0F) {
        ServerProcessLatency = other.ServerProcessLatency;
      }
      frameNumber_.Add(other.frameNumber_);
      if (other.ClientTimeStamp != 0L) {
        ClientTimeStamp = other.ClientTimeStamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            objects_.AddEntriesFrom(input, _repeated_objects_codec);
            break;
          }
          case 16: {
            NumObjects = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            removeIndices_.AddEntriesFrom(input, _repeated_removeIndices_codec);
            break;
          }
          case 37: {
            ServerProcessLatency = input.ReadFloat();
            break;
          }
          case 42:
          case 40: {
            frameNumber_.AddEntriesFrom(input, _repeated_frameNumber_codec);
            break;
          }
          case 48: {
            ClientTimeStamp = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            objects_.AddEntriesFrom(ref input, _repeated_objects_codec);
            break;
          }
          case 16: {
            NumObjects = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            removeIndices_.AddEntriesFrom(ref input, _repeated_removeIndices_codec);
            break;
          }
          case 37: {
            ServerProcessLatency = input.ReadFloat();
            break;
          }
          case 42:
          case 40: {
            frameNumber_.AddEntriesFrom(ref input, _repeated_frameNumber_codec);
            break;
          }
          case 48: {
            ClientTimeStamp = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Status : pb::IMessage<Status>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Status> _parser = new pb::MessageParser<Status>(() => new Status());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Status> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status(Status other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Status Clone() {
      return new Status(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private bool message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Status);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Status other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message != false) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message != false) {
        output.WriteRawTag(8);
        output.WriteBool(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message != false) {
        output.WriteRawTag(8);
        output.WriteBool(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Status other) {
      if (other == null) {
        return;
      }
      if (other.Message != false) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Message = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Message = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioFile : pb::IMessage<AudioFile>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioFile> _parser = new pb::MessageParser<AudioFile>(() => new AudioFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::XrVis.VisReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioFile(AudioFile other) : this() {
      chunkData_ = other.chunkData_;
      textQuery_ = other.textQuery_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioFile Clone() {
      return new AudioFile(this);
    }

    /// <summary>Field number for the "chunk_data" field.</summary>
    public const int ChunkDataFieldNumber = 1;
    private pb::ByteString chunkData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString ChunkData {
      get { return chunkData_; }
      set {
        chunkData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "textQuery" field.</summary>
    public const int TextQueryFieldNumber = 2;
    private string textQuery_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TextQuery {
      get { return textQuery_; }
      set {
        textQuery_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChunkData != other.ChunkData) return false;
      if (TextQuery != other.TextQuery) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChunkData.Length != 0) hash ^= ChunkData.GetHashCode();
      if (TextQuery.Length != 0) hash ^= TextQuery.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChunkData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ChunkData);
      }
      if (TextQuery.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TextQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChunkData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ChunkData);
      }
      if (TextQuery.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TextQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChunkData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ChunkData);
      }
      if (TextQuery.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextQuery);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioFile other) {
      if (other == null) {
        return;
      }
      if (other.ChunkData.Length != 0) {
        ChunkData = other.ChunkData;
      }
      if (other.TextQuery.Length != 0) {
        TextQuery = other.TextQuery;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ChunkData = input.ReadBytes();
            break;
          }
          case 18: {
            TextQuery = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ChunkData = input.ReadBytes();
            break;
          }
          case 18: {
            TextQuery = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
