// <auto-generated>
//     Generated gRPC client stubs for vis.proto.
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
using grpc = global::Grpc.Core;

namespace XrVis
{
    public static partial class VisualizerServer
    {
        static readonly string __ServiceName = "xrVis.VisualizerServer";

        static readonly grpc::Marshaller<AudioFile> __Marshaller_AudioFile =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                AudioFile.Parser.ParseFrom);

        static readonly grpc::Marshaller<allPointClouds> __Marshaller_allPointClouds =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                allPointClouds.Parser.ParseFrom);

        static readonly grpc::Method<AudioFile, allPointClouds> __Method_clientTextQuery =
            new grpc::Method<AudioFile, allPointClouds>(
                grpc::MethodType.ClientStreaming, __ServiceName,
                "clientTextQuery",
                __Marshaller_AudioFile, __Marshaller_allPointClouds);

        public partial class VisualizerServerClient : grpc::ClientBase<VisualizerServerClient>
        {
            public VisualizerServerClient(grpc::ChannelBase channel) : base(channel) { }
            public VisualizerServerClient(grpc::CallInvoker callInvoker) : base(callInvoker) { }
            protected VisualizerServerClient() : base() { }
            protected VisualizerServerClient(ClientBaseConfiguration configuration) : base(configuration) { }

            public virtual grpc::AsyncClientStreamingCall<AudioFile, allPointClouds>
                clientTextQuery(grpc::Metadata headers = null,
                    System.DateTime? deadline = null,
                    System.Threading.CancellationToken cancellationToken = default)
            {
                return CallInvoker.AsyncClientStreamingCall(
                    __Method_clientTextQuery,
                    null, new grpc::CallOptions(headers, deadline, cancellationToken));
            }

            protected override VisualizerServerClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new VisualizerServerClient(configuration);
            }
        }
    }
}
