// <auto-generated>
//     Generated gRPC client stubs for xr_service.proto.
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
using grpc = global::Grpc.Core;

namespace Xr
{
    public static partial class XrService
    {
        static readonly string __ServiceName = "xr.XrService";

        static readonly grpc::Marshaller<UpstreamSyncMessage_dataset> __Marshaller_UpstreamSyncMessage_dataset =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                UpstreamSyncMessage_dataset.Parser.ParseFrom);

        static readonly grpc::Marshaller<VideoStatus> __Marshaller_VideoStatus =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                VideoStatus.Parser.ParseFrom);

        static readonly grpc::Marshaller<UpstreamSyncMessage> __Marshaller_UpstreamSyncMessage =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                UpstreamSyncMessage.Parser.ParseFrom);

        static readonly grpc::Marshaller<UpstreamSyncMessage_quest> __Marshaller_UpstreamSyncMessage_quest =
            grpc::Marshallers.Create(
                (arg) => Google.Protobuf.MessageExtensions.ToByteArray(arg),
                UpstreamSyncMessage_quest.Parser.ParseFrom);

        static readonly grpc::Method<UpstreamSyncMessage_dataset, VideoStatus> __Method_UploadSyncMessage_dataset =
            new grpc::Method<UpstreamSyncMessage_dataset, VideoStatus>(
                grpc::MethodType.ClientStreaming, __ServiceName,
                "UploadSyncMessage_dataset",
                __Marshaller_UpstreamSyncMessage_dataset, __Marshaller_VideoStatus);

        static readonly grpc::Method<UpstreamSyncMessage, VideoStatus> __Method_UploadSyncMessage =
            new grpc::Method<UpstreamSyncMessage, VideoStatus>(
                grpc::MethodType.ClientStreaming, __ServiceName,
                "UploadSyncMessage",
                __Marshaller_UpstreamSyncMessage, __Marshaller_VideoStatus);

        static readonly grpc::Method<UpstreamSyncMessage_quest, VideoStatus> __Method_UploadSyncMessage_quest =
            new grpc::Method<UpstreamSyncMessage_quest, VideoStatus>(
                grpc::MethodType.ClientStreaming, __ServiceName,
                "UploadSyncMessage_quest",
                __Marshaller_UpstreamSyncMessage_quest, __Marshaller_VideoStatus);

        public partial class XrServiceClient : grpc::ClientBase<XrServiceClient>
        {
            public XrServiceClient(grpc::ChannelBase channel) : base(channel) { }
            public XrServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker) { }
            protected XrServiceClient() : base() { }
            protected XrServiceClient(ClientBaseConfiguration configuration) : base(configuration) { }

            public virtual grpc::AsyncClientStreamingCall<UpstreamSyncMessage_dataset, VideoStatus>
                UploadSyncMessage_dataset(grpc::Metadata headers = null,
                    System.DateTime? deadline = null,
                    System.Threading.CancellationToken cancellationToken = default)
            {
                return CallInvoker.AsyncClientStreamingCall(
                    __Method_UploadSyncMessage_dataset,
                    null, new grpc::CallOptions(headers, deadline, cancellationToken));
            }

            public virtual grpc::AsyncClientStreamingCall<UpstreamSyncMessage, VideoStatus>
                UploadSyncMessage(grpc::Metadata headers = null,
                    System.DateTime? deadline = null,
                    System.Threading.CancellationToken cancellationToken = default)
            {
                return CallInvoker.AsyncClientStreamingCall(
                    __Method_UploadSyncMessage,
                    null, new grpc::CallOptions(headers, deadline, cancellationToken));
            }

            public virtual grpc::AsyncClientStreamingCall<UpstreamSyncMessage_quest, VideoStatus>
                UploadSyncMessage_quest(grpc::Metadata headers = null,
                    System.DateTime? deadline = null,
                    System.Threading.CancellationToken cancellationToken = default)
            {
                return CallInvoker.AsyncClientStreamingCall(
                    __Method_UploadSyncMessage_quest,
                    null, new grpc::CallOptions(headers, deadline, cancellationToken));
            }

            protected override XrServiceClient NewInstance(ClientBaseConfiguration configuration)
            {
                return new XrServiceClient(configuration);
            }
        }
    }
}
